export const GET_LOGIN_USER_INFO = 'GET_LOGIN_USER_INFO';
export const SAVE_LOGIN_USERS_DETAILS_SUCCESS = 'SAVE_LOGIN_USERS_DETAILS_SUCCESS';
export const SAVE_LOGIN_USERS_DETAILS_FAILURE = 'SAVE_LOGIN_USERS_DETAILS_FAILURE';

// Static Dropdown Constants
export const GET_ETHNICITY_LIST_REQUEST = 'GET_ETHNICITY_LIST_REQUEST';
export const GET_ETHNICITY_LIST_SUCCESS = 'GET_ETHNICITY_LIST_SUCCESS';
export const GET_ETHNICITY_LIST_FAILURE = 'GET_ETHNICITY_LIST_FAILURE';

// Employee Form Constants
export const EMPLOYEE_FORM_REQUEST = 'EMPLOYEE_FORM_REQUEST';
export const EMPLOYEE_FORM_SUCCESS = 'EMPLOYEE_FORM_SUCCESS';
export const EMPLOYEE_FORM_FAILURE = 'EMPLOYEE_FORM_FAILURE';

export const GET_GENDER_LIST_REQUEST = 'GET_GENDER_LIST_REQUEST';
export const GET_GENDER_LIST_SUCCESS = 'GET_GENDER_LIST_SUCCESS';
export const GET_GENDER_LIST_FAILURE = 'GET_GENDER_LIST_FAILURE';

export const GET_NATIONALITY_LIST_REQUEST = 'GET_NATIONALITY_LIST_REQUEST';
export const GET_NATIONALITY_LIST_SUCCESS = 'GET_NATIONALITY_LIST_SUCCESS';
export const GET_NATIONALITY_LIST_FAILURE = 'GET_NATIONALITY_LIST_FAILURE';

export const GET_CLINICWARD_LIST_REQUEST = 'GET_CLINICWARD_LIST_REQUEST';
export const GET_CLINICWARD_LIST_SUCCESS = 'GET_CLINICWARD_LIST_SUCCESS';
export const GET_CLINICWARD_LIST_FAILURE = 'GET_CLINICWARD_LIST_FAILURE';

export const GET_TITLEPREFIX_LIST_REQUEST = 'GET_TITLEPREFIX_LIST_REQUEST';
export const GET_TITLEPREFIX_LIST_SUCCESS = 'GET_TITLEPREFIX_LIST_SUCCESS';
export const GET_TITLEPREFIX_LIST_FAILURE = 'GET_TITLEPREFIX_LIST_FAILURE';

export const GET_DISCIPLINE_LIST_REQUEST = 'GET_DISCIPLINE_LIST_REQUEST';
export const GET_DISCIPLINE_LIST_SUCCESS = 'GET_DISCIPLINE_LIST_SUCCESS';
export const GET_DISCIPLINE_LIST_FAILURE = 'GET_DISCIPLINE_LIST_FAILURE';

export const GET_SUBDISCIPLINE_LIST_REQUEST = 'GET_SUBDISCIPLINE_LIST_REQUEST';
export const GET_SUBDISCIPLINE_LIST_SUCCESS = 'GET_SUBDISCIPLINE_LIST_SUCCESS';
export const GET_SUBDISCIPLINE_LIST_FAILURE = 'GET_SUBDISCIPLINE_LIST_FAILURE';

export const GET_ORDERSTATUS_LIST_REQUEST = 'GET_ORDERSTATUS_LIST_REQUEST';
export const GET_ORDERSTATUS_LIST_SUCCESS = 'GET_ORDERSTATUS_LIST_SUCCESS';
export const GET_ORDERSTATUS_LIST_FAILURE = 'GET_ORDERSTATUS_LIST_FAILURE';

// Theme Setting Constants
export const THEME_SETTING_DARK = 'THEME_SETTING_DARK';
export const THEME_SETTING_LIGHT = 'THEME_SETTING_LIGHT';

export const GET_COUNTRY = 'GET_COUNTRY';
export const POST_COUNTRY = 'POST_COUNTRY';
export const GET_OFFICE = 'GET_OFFICE';
export const POST_OFFICE = 'POST_OFFICE';
export const GET_BUSINESS = 'GET_BUSINESS';
export const POST_BUSINESS = 'POST_BUSINESS';
export const GET_CONTRACT = 'GET_CONTRACT';
export const POST_CONTRACTS = 'POST_CONTRACTS';
export const GET_PROJECT_STATUS = 'GET_PROJECT_STATUS';
export const POST_PROJECT_STATUS = 'POST_PROJECT_STATUS';
export const GET_STATUS = 'GET_STATUS';
export const POST_STATUS = 'POST_STATUS';
export const GET_LOCATION = 'GET_LOCATION';
export const POST_LOCATION = 'POST_LOCATION';
export const GET_SERVICEMEN = 'GET_SERVICEMEN';
export const POST_SERVICEMEN = 'POST_SERVICEMEN';
export const POST_SERVICE_SUBJECT = 'POST_SERVICE_SUBJECT';
export const GET_LEGAL_ENTITIES = 'GET_LEGAL_ENTITIES';
export const POST_LEGAL_ENTITIES = 'POST_LEGAL_ENTITIES';
export const GET_BUSINESS_TYPES = 'GET_BUSINESS_TYPES';
export const GET_REGIONS = 'GET_REGIONS';
export const GET_REGIONS_WITH_HIERARCHY = 'GET_REGIONS_WITH_HIERARCHY';
export const GET_BUSINESS_SUB_TYPES = 'GET_BUSINESS_SUB_TYPES';
export const SAVE_ROLEWISE_MENU = 'SAVE_ROLEWISE_MENU';
export const SAVE_ROLES = 'SAVE_ROLES';
export const SAVE_SALESMANS = 'SAVE_SALESMANS';
export const SAVE_SERVICEMANS = 'SAVE_SERVICEMANS';
export const GET_CURRIENCY_CODES = 'GET_CURRIENCY_CODES';
export const GET_FUNDING_TYPES = 'GET_FUNDING_TYPES';
export const GET_SERVICE_ORDER_STATUS = 'GET_SERVICE_ORDER_STATUS';

// Commercial Modules
export const GET_SALESMEN = 'GET_SALESMEN';
export const GET_LEGALENTITIES = 'GET_LEGALENTITIES';
export const GET_CUSTOMER_CLASSIFICATIONS = 'GET_CUSTOMER_CLASSIFICATIONS';
export const GET_CUSTOMER_GROUPS = 'GET_CUSTOMER_GROUPS';
export const CUSTOMER_RECORDS = 'CUSTOMER_RECORDS';
export const CUSTOMER_LOCATIONS = 'CUSTOMER_LOCATIONS';
export const CUSTOMER_CONTACTS = 'CUSTOMER_CONTACTS';
export const LOCATION_CONTACTS = 'LOCATION_CONTACTS';

// Loader redux state
export const IS_DATA_LOADING = 'IS_DATA_LOADING';
