export const API_V1 = 'v1/reza';

export const APIS = {
  GET_LEGAL_ENTITIES: 'legalentities/getforddl',
  GET_COUNTRIES: 'countries/getforddl',
  GET_REGIONS: 'regions/getforddl',
  GET_CURRIENCY_CODES: 'currencycodes/getforddl',
  FUNDING_TYPES: 'fundingtype/getforddl',
  GET_BUSINESS_TYPES: 'businesstypes/getforddl',
  GET_BUSINESS_SUB_TYPES: 'businesssubtypes/getforddl',
  GET_EMPLOYEES: 'employees/list',
  GET_RANDOM_COLOR_CODE: 'colorcode/get',
  VALIDATE_COLOR_CODE: 'colorcode/validatecolor',
  GET_USERS: 'getuserlist', // This API is still need pageIndex and pageSize
  GET_ROLEWISE_MENU: 'uicontrols/getrolemenulist',
  GET_ROLES: 'getrolelist',
  GET_REGIONS_WITH_HEIRARCHY: 'regions/getbyhierarchyforddl',
  GET_USER_PROFILE_DETAILS: 'uicontrols/getuserprofiledetails',
  CHANGE_PASSWORD: 'manage/changePassword',
  GET_MOBILE_WAREHOUSE_DATA: 'manage/mobileWarehouse',
  GET_MOBILE_WAREHOUSE_ITEM_LIST: 'manage/mobileWarehouseItenList',
  UPDATE_DISPLAYNAME: 'users/updatedisplayname',
  GET_CUSTOMERS: 'customers/list',
  UPDATE_CUSTOMER_SHORT_NAME: 'customers/updatecustomershortname',
  GET_SALESMAN: 'salesman/list',
  GET_SALESMAN_DDL: 'salesman/getforddl',
  GET_SERVICEMAN: 'serviceman/list',
  GET_SIGNATORYINFORMATION: 'customers/signatoryinformation',
  GET_COUNTRYLIST: 'countries/list',
  GET_REGIONLIST: 'regions/list',
  GET_SERVICEMAN_DDL: 'serviceman/getforddl', // Need to figure out where to use
  ADD_UPDATE_USER: 'users/addorupdate', // Need to verify Payload
  LOG_USER_ACTIVITY: 'user/logactivity',
  PROJECT_MANAGEMENT_CONTRACT: 'project-management/contract',
  NEW_PROJECT_DETAILS: 'newprojectdetails',
  PROJECT_TYPES: 'common/projecttypes',
  PROJECT_STATUSES: 'common/projectstatuses',
  CUSTOMER_MANAGEMENT_LOCATION: 'customer-management/customer/locations',
  SIGNOTORIES: 'signatories',
  PROJECTS: 'project-management/getprojects',
  PREFERRED_TIMES: 'preferredtimes/getforddl',
  ADD_NEW_PROJECT: 'project-management/projects',
  GET_PROJECT_DETAILS: 'project-management/get-project-details',
  SEARCH_PROJECTS: 'project-management/search-projects',
  UPDATE_PROJECTS: 'project-management/update-project',
  SERVICE_FREQUENCIES: 'common/servicefrequencies',
  SERVICE_OCCURRENCES: 'service-occurances',
  GET_USERLIST: 'leave-management/userslist',
  ADD_LEAVE: 'leave-management/addemployeeleaves',
  LEAVES_DATA: 'leave-management/leaves',
  REMOVE_LEAVE: 'leave-management/removeemployeeleave',
  CREATE_SERVICE_ORDERS: 'service-management/createserviceorders',
  SERVICE_LEVELS: 'service-management/service-levels',
  SERVICE_SUBJECTS: 'service-management/service-subjects',
  SERVICE_ORDERS_DATES: 'serviceorderdates/getforddl?projectId=',
  GET_SCHEDULE_ORDERS: 'service-management/getscheduledorders',
  GET_SERVICE_ORDER_TASK: 'project-management/serviceordertask',
  GET_ZONES: 'zones',
  SERVICE_ORDER_TASKS: 'service-management/service-ordertasks',
  SERVICE_ORDER_TASK_ITEMS_DDL: 'service-management/service-subject/taskitemsddl',
  SERVICE_ORDER_TASK_ITEMS: 'service-management/service-subject/taskitems',
  SAVE_SERVICE_SUBJECT: 'service-management/addservicesubject',
  GET_SERVICE_ORDER_STATUS: 'serviceorderstatus/getforddl',
  GET_SCHEDULE_MAPVIEW_ORDERS: 'service-management/getscheduledmapviews',
  // GET_SCHEDULE_MAPVIEW_ORDERS: '/project-management/get-previous-project-details?projectId={{projectId}}',
  GET_PROJECT_DETAILS_FROM_PREVIOUS_PROJECT: 'project-management/get-previous-project-details',
  GET_SERVICE_DETAIL_CARD: 'service-management/get-servicedetails',
  GET_SERVICE_ORDERS_WITH_PROJECT_ID: 'service-management/get-sheduleserviceorder?projectId',
  GET_TASK_DETAILS_BY_SERVICE_ORDER: 'service-management/edit-schedule/gettaskdetailsbyserviceorder',
  GET_ITEMS_WITH_PREFERENCE: 'service-management/edit-schedule/getitemswithpreferrence',
  GET_TASK_ITEM_DETAILS: 'service-management/edit-schedule/taskitemdetails',
  GET_SERVICEMEN_ON_LEAVE: 'service-management/edit-schedule/servicemenonleave',
  GET_SHIFT_NEXT_SERVICES: 'service-management/edit-schedule/getotherserviceorderlist',
  REMOVE_SERVICE_ORDER: 'service-management/removeserviceorder?serviceorderId',
  REMOVE_SERVICE_ORDER_TASK: 'project-management/removeserviceordertasks',
  CREATE_ADDITIONAL_SERVICE_ORDER: 'service-management/createadditionalserviceorder',
  GET_SERVICE_SUBJECTS: 'service-management/getservicesubjectsforproject?projectId',
  UPDATE_ZONE_FIRST_SERVICE_DATE: 'service-management/editproject-updateorderdetails',
  UPDATE_SERVICE_ORDER: 'service-management/updateserviceorder',
  PREFERRED_ITEMS_FOR_ITEM: 'service-management/edit-schedule/getpreferreditems?itemId',
  REFRESH_CUST_DATA: 'customer-management/refreshcustomerdata?customerId',
  SAVE_EDIT_SCHEDULE: 'service-management/edit-schedule/update-schedule',
  DELETE_TASKITEM: 'service-management/removeserviceordertaskitem?serviceorderTaskItemId',
  GET_SERVICE_SUB_ORDER_TASK_DETAILS: 'service-management/edit-servicesubject/getservicesubjectordertasksdetails',
  COPY_SERVICE_ORDER: 'service-management/add-project/copyservicedetails',
  GET_CUSTOMERS_DDL: 'inventory-management/getcustomerddl',
  GET_MPL: 'inventory-management/getmaterialpickinglist',
  GET_STOCK_DETAILED_LIST: 'inventory-management/getstockdetailedList',
  SAVE_EDIT_SERVICE_SUBJECT: 'service-management/edit-servicesubject/updateserviceordertasks',
  REMOVE_SERVICE_SUBJECT_TASK: 'service-management/removeserviceordertask?serviceordertaskId',
  GET_GLOBAL_ITEMS: 'inventory-management/getitemsddl',
  VALIDATE_SS_QUANTITY: 'service-management/edit-servicesubject/validateservicesubjectquantity',

  // CUSTOMER VIEW API's
  GET_CUSTOMER_GROUPS: 'customer-management/getcustomergroups?LegalEntityId=',
  GET_SALESMEN: 'customer-management/getsalesmen',
  GET_LEGAL_ENTITIES_BY_REGION: 'customer-management/getlegalentitiesbyregion',
  GET_CUSTOMER_CLASSIFICATIONS: 'customer-management/getcustomerclassifications?LegalEntityId=',
  GET_FILTERED_CUSTOMERS: 'customer-management/getfilteredcustomers',
  GET_LOCATIONS: 'customer-management/getlocationswithcontacts?customerId=',

  // CUSTOMER ADD API's
  GET_DELIVERY_MODES: 'customer-management/getdeliverymodes?legalEntityId=',
  GET_PAYMENT_TERMS: 'customer-management/getpaymentterms?legalEntityId=',
  GET_COLLECTORS: 'customer-management/getcollectors?legalEntityId=',
  GET_CURRENCIES: 'customer-management/getcurrencies?legalEntityId=',
  GET_BUSINESS_SECTORS: 'customer-management/getbusinesssectors?legalEntityId=',
  GET_BUSINESS_INDUSTRIES: 'customer-management/getbusinessindustries?legalEntityId=',
  GET_INCOTERMS: 'customer-management/getincoterms?legalEntityId=',
  GET_ADD_CUSTOMERS: 'customer-management/getcustomers',
  GET_ADD_LOCATIONS: 'customer-management/getlocationsforcustomer',
  GET_ORGANIZATION_IDENTIFICATION_TYPES: 'customer-management/getorganizationidentificationtypes?legalEntityId=',
  GET_REGION_LIST: 'customer-management/getregionsbylegalentity?legalEntityId=',
  ADD_CUSTOMER: 'customer-management/addupdatecustomer',
  GET_ADD_LOCATIONS_NAME: 'customer-management/getlocationsforcustomer',
  GET_HAS_LOCATION_CONTACT: 'customer-management/haslocationcontacts?customerLocationId=',
  GET_COUNTRY_PHONE_CODE: 'customer-management/getcountryphonecodes',
  ADD_LOCATION_CONTACT: 'customer-management/addupdatelocationcontact',
  GET_SALES_TAX_GROUPS: 'customer-management/getsalestaxgroupsbylegalentity?legalEntityId=',
  UPLOAD_ATTACHMENTS: 'customer-management/uploadcustomerattachment',
  GET_LOCATION_NAME_LIST: 'customer-management/locations',
  ADD_UPDATE_CUSTOMER_LOCATION: 'customer-management/addupdatecustomerlocation',
  GET_CUTOMER_DETAILS: 'customer-management/getcustomerdetails?customerId=',
  ADD_CUSTOMER_CONTACT: 'customer-management/addupdatecustomercontact',
  DOWNLOAD_CUSTOMER_ATTACHMENT: 'customer-management/downloadcustomerattachment?guid=',
  GET_LOCATION_DETAILS: 'customer-management/getlocationdetails?customerLocationId=',
  GET_LOCATION_CONTACT_DETAILS: 'customer-management/getlocationcontactdetails?customerLocationContactId=',
  GET_CUSTOMER_CONTACT_DETAILS: 'customer-management/getcustomercontactdetails?customerContactId=',
  DELETE_CUSTOMER_ATTACHMENT: 'customer-management/deletecustomerattachment?attachmentId=',
  APPROVE_CUSTOMER: 'customer-management/approvecustomer',
  SUBMIT_FOR_APPROVAL: 'customer-management/submitforapproval?customerId=',
  RESUBMIT_FOR_APPROVAL: 'customer-management/resubmitforapproval?customerId=', // &isEscalate=false
  REJECT_CUSTOMER: 'customer-management/rejectcustomer?customerId=' // &isEscalate=false
};
