export const InternalUserTableData = [
  {
    id: 1,
    name: 'Mohammad Qasem Abou',
    userName: 'mmhost.1301',
    email: 'matjaz.msrek@kivi.si',
    countryCode: '+971',
    mobileNo: '031546569',
    shortName: 'Mohammad',
    employeeId: 1001,
    legalEntity: 'L1',
    role: 'Delivery Driver',
    backColor: '',
    textColor: ''
  },
  {
    id: 2,
    name: 'Leighton Clive Darren',
    userName: 'darren.1001',
    email: 'cpam.hygiene@rezagroup.com',
    countryCode: '+966',
    mobileNo: '+966553691440',
    shortName: 'Darren',
    employeeId: 1002,
    legalEntity: 'L2',
    role: 'IT Admin',
    backColor: '',
    textColor: ''
  },
  {
    id: 3,
    name: 'Abdul Majid Abdulaziz',
    userName: 'naik.1002',
    email: 'wpam.hygiene@rezagroup.com',
    countryCode: '+974',
    mobileNo: '+966504603776',
    shortName: 'Majid',
    employeeId: 1003,
    legalEntity: 'L3',
    role: 'Super Admin',
    backColor: '',
    textColor: ''
  },
  {
    id: 4,
    name: 'Nabeel Subhi Asad',
    userName: 'nabeel.1004',
    email: 'export.hygiene@rezagroup.com',
    countryCode: '+974',
    mobileNo: '+96653500027',
    shortName: 'Nabeel',
    employeeId: 1004,
    legalEntity: 'L5',
    role: 'Super Admin',
    backColor: '',
    textColor: ''
  },
  {
    id: 5,
    name: 'Aristotle Aycardo Balde',
    userName: 'aris.1005',
    email: 'aris.hygiene@rezagroup.com',
    countryCode: '+974',
    mobileNo: '+966531406886',
    shortName: 'Aris',
    employeeId: 1005,
    legalEntity: 'L5',
    role: 'Super Admin',
    backColor: '',
    textColor: ''
  },
  {
    id: 6,
    name: 'Poobalan Anthony Dilraj',
    userName: 'dilrag.1006',
    email: 'dilraj.hygiene@rezagroup.com',
    countryCode: '+974',
    mobileNo: '+966504900250',
    shortName: 'Dilraj',
    employeeId: 1006,
    legalEntity: 'L6',
    role: 'Super Admin',
    backColor: '',
    textColor: ''
  },
  {
    id: 7,
    name: 'Mohammed Ibrahim Mohammed',
    userName: 'ibrahim.1007',
    email: 'ibrahim.hygiene@rezagroup.com',
    countryCode: '+974',
    mobileNo: '+966501780600',
    shortName: 'Ibrahim',
    employeeId: 1007,
    legalEntity: 'L7',
    role: 'Super Admin',
    backColor: '',
    textColor: ''
  },
  {
    id: 8,
    name: 'Azharuddin Ali Mir',
    userName: 'azhar.1008',
    email: 'azeezmthodi@gmail.com',
    countryCode: '+974',
    mobileNo: '+966550347864',
    shortName: 'Azhar',
    employeeId: 1008,
    legalEntity: 'L4',
    role: 'Super Admin',
    backColor: '',
    textColor: ''
  },
  {
    id: 9,
    name: 'Andrew James Turner',
    userName: 'andy.1009',
    email: 'andrew.hygiene@rezagroup.com',
    countryCode: '+974',
    mobileNo: '+966501910715',
    shortName: 'Andy',
    employeeId: 1009,
    legalEntity: 'L9',
    role: 'Super Admin',
    backColor: '',
    textColor: ''
  },
  {
    id: 10,
    name: 'Samir Abdelhamid ismail',
    userName: 'samir.1010',
    email: 'samir.hygiene@rezagroup.com',
    countryCode: '+974',
    mobileNo: '+966550395524',
    shortName: 'Samir',
    employeeId: 1010,
    legalEntity: 'L10',
    role: 'Super Admin',
    backColor: '',
    textColor: ''
  },
  {
    id: 11,
    name: 'Muhammad Bilal Qasim',
    userName: 'marco.1011',
    email: 'marco.lubes@rezagroup.com',
    countryCode: '+971',
    mobileNo: '+971569921272',
    shortName: 'Debabrata',
    employeeId: 1011,
    legalEntity: 'L11',
    role: 'Super Admin',
    backColor: '',
    textColor: ''
  },
  {
    id: 12,
    name: 'Marco Quebrata Quesea',
    userName: 'marco.1012',
    email: 'marco.lubes.@rezagroup.com',
    countryCode: '+971',
    mobileNo: '+971569921272',
    shortName: 'Marco',
    employeeId: 1012,
    legalEntity: 'L12',
    role: 'Super Admin',
    backColor: '',
    textColor: ''
  },
  {
    id: 13,
    name: 'Debabrata Chakraborty Nando',
    userName: 'debabrata.1013',
    email: 'debbrata.hygiene@rezagroup.com',
    countryCode: '+974',
    mobileNo: '+966550503960',
    shortName: 'debbrata',
    employeeId: 1013,
    legalEntity: 'L13',
    role: 'Super Admin',
    backColor: '',
    textColor: ''
  },
  {
    id: 14,
    name: 'Declan Lee',
    userName: 'declan.1014',
    email: 'declan.rezaindsol@rezagroup.com',
    countryCode: '+974',
    mobileNo: '+966539154443',
    shortName: 'Declan',
    employeeId: 1014,
    legalEntity: 'L14',
    role: 'Super Admin',
    backColor: '',
    textColor: ''
  },
  {
    id: 15,
    name: 'Mohamad Hazar Hashmin',
    userName: 'hasmin.1015',
    email: 'hasmin.hygiene@rezagroup.com',
    countryCode: '+974',
    mobileNo: '+966559436217',
    shortName: 'Hashim',
    employeeId: 1015,
    legalEntity: 'L15',
    role: 'Super Admin',
    backColor: '',
    textColor: ''
  }
];
